version: '3.5'
services:
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 27017:$DB_PORT
    volumes:
      - ./db-mongodb:/data/db
  redis_cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - ./cache:/data
volumes:
  db-mongodb:
  cache:
